USE [master]
GO

/****** Object:  Database [studentInfo]    Script Date: 01/11/2023 3:51:11 pm ******/
CREATE DATABASE [studentInfo]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'studentInfo', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\studentInfo.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'studentInfo_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\studentInfo_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [studentInfo].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [studentInfo] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [studentInfo] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [studentInfo] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [studentInfo] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [studentInfo] SET ARITHABORT OFF 
GO

ALTER DATABASE [studentInfo] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [studentInfo] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [studentInfo] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [studentInfo] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [studentInfo] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [studentInfo] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [studentInfo] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [studentInfo] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [studentInfo] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [studentInfo] SET  DISABLE_BROKER 
GO

ALTER DATABASE [studentInfo] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [studentInfo] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [studentInfo] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [studentInfo] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [studentInfo] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [studentInfo] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [studentInfo] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [studentInfo] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [studentInfo] SET  MULTI_USER 
GO

ALTER DATABASE [studentInfo] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [studentInfo] SET DB_CHAINING OFF 
GO

ALTER DATABASE [studentInfo] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [studentInfo] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [studentInfo] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [studentInfo] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [studentInfo] SET QUERY_STORE = OFF
GO

ALTER DATABASE [studentInfo] SET  READ_WRITE 
GO

